
// SIGNUP ACTIONS
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

// LOGIN ACTIONS
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// CREATE_ACCOUNT ACTIONS
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_ERROR = 'CREATE_ACCOUNT_ERROR';

// CREATE_CATEGORY ACTIONS
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_ERROR = 'CREATE_CATEGORY_ERROR';

// CREATE_EXPENSE ACTIONS
export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS';
export const CREATE_EXPENSE_ERROR = 'CREATE_EXPENSE_ERROR';

// CREATE_EXPENSE ACTIONS
export const CREATE_INCOME_SUCCESS = 'CREATE_INCOME_SUCCESS';
export const CREATE_INCOME_ERROR = 'CREATE_INCOME_ERROR';

// CHANGE_PASSWORD ACTIONS
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';

// GET_TRANSACTION_BY_RANGE ACTIONS   get_transactions_by_range
export const GET_TRANSACTION_BY_RANGE_SUCCESS = 'GET_TRANSACTION_BY_RANGE_SUCCESS';
export const GET_TRANSACTION_BY_RANGE_ERROR = 'GET_TRANSACTION_BY_RANGE_ERROR';

//GET_ALL_TRANSACTION ACTIONS
export const GET_ALL_TRANSACTION_SUCCESS = 'GET_ALL_TRANSACTION_SUCCESS';
export const GET_ALL_TRANSACTION_ERROR = 'GET_ALL_TRANSACTION_ERROR';